/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedSubscribersIndexRouteImport } from './routes/_authenticated/subscribers/index'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates/new'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates/$id'
import { Route as AuthenticatedSubscribersNewRouteImport } from './routes/_authenticated/subscribers/new'
import { Route as AuthenticatedSubscribersIdRouteImport } from './routes/_authenticated/subscribers/$id'
import { Route as AuthenticatedListsNewRouteImport } from './routes/_authenticated/lists/new'
import { Route as AuthenticatedListsIdRouteImport } from './routes/_authenticated/lists/$id'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns/new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscribersIndexRoute =
  AuthenticatedSubscribersIndexRouteImport.update({
    id: '/subscribers/',
    path: '/subscribers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscribersNewRoute =
  AuthenticatedSubscribersNewRouteImport.update({
    id: '/subscribers/new',
    path: '/subscribers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscribersIdRoute =
  AuthenticatedSubscribersIdRouteImport.update({
    id: '/subscribers/$id',
    path: '/subscribers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListsNewRoute = AuthenticatedListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListsIdRoute = AuthenticatedListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
  '/lists/new': typeof AuthenticatedListsNewRoute
  '/subscribers/$id': typeof AuthenticatedSubscribersIdRoute
  '/subscribers/new': typeof AuthenticatedSubscribersNewRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
  '/subscribers/': typeof AuthenticatedSubscribersIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
  '/lists/new': typeof AuthenticatedListsNewRoute
  '/subscribers/$id': typeof AuthenticatedSubscribersIdRoute
  '/subscribers/new': typeof AuthenticatedSubscribersNewRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/lists': typeof AuthenticatedListsIndexRoute
  '/subscribers': typeof AuthenticatedSubscribersIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/lists/$id': typeof AuthenticatedListsIdRoute
  '/_authenticated/lists/new': typeof AuthenticatedListsNewRoute
  '/_authenticated/subscribers/$id': typeof AuthenticatedSubscribersIdRoute
  '/_authenticated/subscribers/new': typeof AuthenticatedSubscribersNewRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
  '/_authenticated/subscribers/': typeof AuthenticatedSubscribersIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/dashboard'
    | '/import-export'
    | '/permissions'
    | '/api/uploadthing'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/lists/$id'
    | '/lists/new'
    | '/subscribers/$id'
    | '/subscribers/new'
    | '/templates/$id'
    | '/templates/new'
    | '/campaigns/'
    | '/lists/'
    | '/subscribers/'
    | '/templates/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/dashboard'
    | '/import-export'
    | '/permissions'
    | '/api/uploadthing'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/lists/$id'
    | '/lists/new'
    | '/subscribers/$id'
    | '/subscribers/new'
    | '/templates/$id'
    | '/templates/new'
    | '/campaigns'
    | '/lists'
    | '/subscribers'
    | '/templates'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-export'
    | '/_authenticated/permissions'
    | '/api/uploadthing'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/lists/$id'
    | '/_authenticated/lists/new'
    | '/_authenticated/subscribers/$id'
    | '/_authenticated/subscribers/new'
    | '/_authenticated/templates/$id'
    | '/_authenticated/templates/new'
    | '/_authenticated/campaigns/'
    | '/_authenticated/lists/'
    | '/_authenticated/subscribers/'
    | '/_authenticated/templates/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscribers/': {
      id: '/_authenticated/subscribers/'
      path: '/subscribers'
      fullPath: '/subscribers/'
      preLoaderRoute: typeof AuthenticatedSubscribersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscribers/new': {
      id: '/_authenticated/subscribers/new'
      path: '/subscribers/new'
      fullPath: '/subscribers/new'
      preLoaderRoute: typeof AuthenticatedSubscribersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscribers/$id': {
      id: '/_authenticated/subscribers/$id'
      path: '/subscribers/$id'
      fullPath: '/subscribers/$id'
      preLoaderRoute: typeof AuthenticatedSubscribersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/new': {
      id: '/_authenticated/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof AuthenticatedListsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lists/$id': {
      id: '/_authenticated/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AuthenticatedListsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedListsIdRoute: typeof AuthenticatedListsIdRoute
  AuthenticatedListsNewRoute: typeof AuthenticatedListsNewRoute
  AuthenticatedSubscribersIdRoute: typeof AuthenticatedSubscribersIdRoute
  AuthenticatedSubscribersNewRoute: typeof AuthenticatedSubscribersNewRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
  AuthenticatedSubscribersIndexRoute: typeof AuthenticatedSubscribersIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedListsIdRoute: AuthenticatedListsIdRoute,
  AuthenticatedListsNewRoute: AuthenticatedListsNewRoute,
  AuthenticatedSubscribersIdRoute: AuthenticatedSubscribersIdRoute,
  AuthenticatedSubscribersNewRoute: AuthenticatedSubscribersNewRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
  AuthenticatedSubscribersIndexRoute: AuthenticatedSubscribersIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
